// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1) {
  return window['go']['main']['App']['AddRoot'](arg1);
}

export function DeleteIncludeRule(arg1) {
  return window['go']['main']['App']['DeleteIncludeRule'](arg1);
}

export function GetEffectiveConfig(arg1) {
  return window['go']['main']['App']['GetEffectiveConfig'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListChangeSets(arg1) {
  return window['go']['main']['App']['ListChangeSets'](arg1);
}

export function ListIncludeRules() {
  return window['go']['main']['App']['ListIncludeRules']();
}

export function ListRoots() {
  return window['go']['main']['App']['ListRoots']();
}

export function RemoveRoot(arg1) {
  return window['go']['main']['App']['RemoveRoot'](arg1);
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function RunDiagnostics(arg1) {
  return window['go']['main']['App']['RunDiagnostics'](arg1);
}

export function ScanRepositories(arg1) {
  return window['go']['main']['App']['ScanRepositories'](arg1);
}

export function ToggleIncludeRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleIncludeRule'](arg1, arg2);
}

export function UpsertIncludeRule(arg1) {
  return window['go']['main']['App']['UpsertIncludeRule'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
