// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitcfg} from '../models';

export function AddRoot(arg1:string):Promise<void>;

export function DeleteIncludeRule(arg1:string):Promise<void>;

export function GetEffectiveConfig(arg1:string):Promise<gitcfg.ConfigMatrix>;

export function Greet(arg1:string):Promise<string>;

export function ListChangeSets(arg1:string):Promise<Array<gitcfg.ChangeSet>>;

export function ListIncludeRules():Promise<Array<gitcfg.IncludeRule>>;

export function ListRoots():Promise<Array<string>>;

export function RemoveRoot(arg1:string):Promise<void>;

export function Rollback(arg1:string):Promise<gitcfg.ChangeSet>;

export function RunDiagnostics(arg1:string):Promise<gitcfg.DiagnosticsReport>;

export function ScanRepositories(arg1:gitcfg.ScanOptions):Promise<Array<gitcfg.Repository>>;

export function ToggleIncludeRule(arg1:string,arg2:boolean):Promise<gitcfg.IncludeRule>;

export function UpsertIncludeRule(arg1:gitcfg.IncludeRule):Promise<gitcfg.IncludeRule>;

export function WriteConfig(arg1:gitcfg.WriteRequest):Promise<gitcfg.ChangeSet>;
